on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened]

name: Add to project

permissions:
  issues: read
  pull-requests: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/rivm-syso/projects/11
          github-token: ${{ secrets.AT_ROvis }}
